$(document).ready(function () {
    var c1 ='<h2>Please select an Option</h2>'

    var Brochure = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/brochures2.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$5,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>3 Revisions</h4><h4>Basic resolution logo</h4><h4>7 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/brochure.jpeg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$7,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>PNG File</h4><h4>3-5 Revisions</h4><h4>High resolution logo</h4><h4>5 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/Brochures-and-Flyers.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$10,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>PNG File</h4><h4>Vector File</h4><h4>7 Revisions</h4><h4>High resolution logo</h4><h4>3 Days Turnaround time</h4><h4>PUB File</h4></div></div>';

    var Business_card = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/business-card2.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$1,500</p></div></figcaption></figure><div class="listing"><h4>1 side</h4><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>3 Revisions</h4><h4>Basic resolution logo</h4><h4>7 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/business-card.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$3,000</p></div></figcaption></figure><div class="listing"><h4>2 sides</h4><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>3-5 Revisions</h4><h4>High resolution logo</h4><h4>5 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/business-card3.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$5,000</p></div></figcaption></figure><div class="listing"><h4>2 sides</h4><h4>3 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>Vector File</h4><h4>7 Revisions</h4><h4>High resolution logo</h4><h4>3 Days Turnaround time</h4><h4>PSD File</h4></div></div><div><h1>What We Need From You:</h1></div><ul><li><p>Company or Business Name & Type.</p></li><li><p>Text information (With grammar correction)</p></li><li><p>Your logo (vector(.png) if possible)</p></li><li><p>Images (if any).</p></li></li><li><p>Your preferred style/theme/color scheme if you have any.</p>   </li></li><li><p>Anything else you feel I need to know in order to make your design AWESOME! </p></li></ul>';

    var Flyers = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/flyer.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$5,000</p></div></figcaption></figure><div class="listing"><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>3 Revisions</h4><h4>Basic resolution logo</h4><h4>7 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/flyer2.JPG" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$7,000</p></div></figcaption></figure><div class="listing"><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>3-5 Revisions</h4><h4>High resolution logo</h4><h4>5 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/flyer3.JPG" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$10,000</p></div></figcaption></figure><div class="listing"><h4>3 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>Vector File</h4><h4>7 Revisions</h4><h4>High resolution logo</h4><h4>3 Days Turnaround time</h4><h4>PSD File</h4></div></div>';

    var Logo = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/logo3.jpg" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$5,000</p></div></figcaption></figure><div class="listing"><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>3 Revisions</h4><h4>Basic resolution logo</h4><h4>7 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/logo2.JPG" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$7,000</p></div></figcaption></figure><div class="listing"><h4>2 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>3-5 Revisions</h4><h4>High resolution logo</h4><h4>5 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/logo.JPG" alt="image" height="142px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$10,000</p></div></figcaption></figure><div class="listing"><h4>3 Design Concepts</h4><h4>Jpeg File</h4><h4>PNG File</h4><h4>Vector File</h4><h4>7 Revisions</h4><h4>High resolution logo</h4><h4>3 Days Turnaround time</h4><h4>PSD File</h4></div></div>';

    var Poster = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/poster1.jpg" alt="image" height="300px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$5,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>3 Revisions</h4><h4>Basic resolution logo</h4><h4>7 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/poster.jpg" alt="image" height="300px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$7,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>PNG File</h4><h4>3-5 Revisions</h4><h4>High resolution logo</h4><h4>5 Days Turnaround time</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/Poster3.jpeg" alt="image" height="300px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$10,000</p></div></figcaption></figure><div class="listing"><h4>Jpeg File</h4><h4>PNG File</h4><h4>Vector File</h4><h4>7 Revisions</h4><h4>High resolution logo</h4><h4>3 Days Turnaround time</h4><h4>PUB File</h4></div></div>';

    var Web_design = '<div class="listing-item"><figure class="image"><img src="uploads/Pricing/webdesigning1.jpg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$540 us annually </p><p1>($45 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>2Gb Disk Space</h4><h4>20Gb Bandwidth</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/Pricing/webdesigning2.jpg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$600 us annually </p><p1>($50 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>5Gb Disk Space</h4><h4>50Gb Bandwidth</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/Pricing/webdesigning3.jpg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$660 us annually </p><p1>($55 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>10Gb Disk Space</h4><h4>100Gb Bandwidth</h4></div></div>';

    var Web_hosting = '<div class="listing-item"><figure class="image"><img src="uploads/pricing/webhostingbasic.jpeg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Basic</h1><p>$540 us annually </p><p1>($45 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>2Gb Disk Space</h4><h4>20Gb Bandwidth</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/webhostingstandard.jpeg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Standard</h1><p>$600 us annually </p><p1>($50 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>5Gb Disk Space</h4><h4>50Gb Bandwidth</h4></div></div><div class="listing-item"><figure class="image"><img src="uploads/pricing/webhostingpremium.jpeg" alt="image" height="180px"; width="142px"><figcaption><div class="Caption"><h1>Premium</h1><p>$660 us annually </p><p1>($55 us  Monthly)</p1></div></figcaption></figure><div class="listing"><h4>Unlimited Domain(eg. TechticsJa.com)</h4><h4><a href="https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/">Free SSL Certificate</a></h4><h4>10Gb Disk Space</h4><h4>100Gb Bandwidth</h4></div></div>';

    var New_building = "";

    var Existing_building = "";

    $('.form_change').change(function(){
        var selectedValue = $(this).val();
        if (selectedValue == "Select")
            $('.hover-table-layout').html(c1);
        else if(selectedValue == 1)
            $('.hover-table-layout').html(Brochure);
        else if(selectedValue == 2)
            $('.hover-table-layout').html(Business_card);
        else if(selectedValue == 3)
            $('.hover-table-layout').html(Flyers);
        else if(selectedValue == 4)
            $('.hover-table-layout').html(Logo);
        else if(selectedValue == 5)
            $('.hover-table-layout').html(Poster);
        else if(selectedValue == 6)
            $('.hover-table-layout').html(Web_design);
        else if(selectedValue == 7)
            $('.hover-table-layout').html(Web_hosting);
        else if(selectedValue == 8)
            $('.hover-table-layout').html(New_building);
        else if(selectedValue == 9)
            $('.hover-table-layout').html(Existing_building);        
    });
});

